project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  search: true
  page-footer:
    center:
      - text: "@Suzette Flantua 2026"
  title: "Suzette Flantua"



  # Custom header for top navigation
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "My Projects"
        menu:
          - text: "Overview of projects"
            href: projects/index.qmd
          - text: "BIODYNAMICS"
            href: projects/BIODYNAMICS/index.qmd
          - text: "CONNECT-EVOLVE"
            href: projects/CONNECT-EVOLVE/index.qmd
          - text: "ECO-SPACE"
            href: projects/ECO-SPACE/index.qmd
          - text: "FOSSILPOL"
            href: projects/FOSSILPOL/index.qmd
          - text: "GEO-BRIDGE"
            href: projects/GEOBRIDGE/index.qmd
          - text: "GLACIMONTIS"
            href: projects/GLACIMONTIS/index.qmd
          - text: "Mini-Encyclopedia of the Paramo-book"
            href: projects/PARAMO-BOOK/index.qmd
          - text: "Global Human Impact"
            href: projects/GLOBAL-HUMAN-IMPACT/index.qmd
          - text: "Latin American Pollen Database"
            href: projects/LAPD/index.qmd
          - text: "Mini-Encyclopedia of the Paramo-book"
            href: projects/PARAMO-BOOK/index.qmd
          - text: "Pantropical dynamics"
            href: projects/PANTROPICAL/index.qmd
          - text: "PPF-Alpine"
            href: projects/PPF-ALPINE/index.qmd
      - text: "My Publications"
        menu:
          - text: "List of publications"
            href: about_me/list_of_publications.qmd
          - text: "CV"
            href: about_me/cv.qmd
      - text: "Outreach"
        href: outreach.qmd
      - text: "Get in touch"
        href: collaborate.qmd


format:
  html:
    theme: darkly
    css: styles.css
    toc: true
