---
title: "My list of publications, comments, expert reports, popular science articles and my theses "
format: 
  html:
    code-fold: false
    code-tools: false
editor: visual
---

### Peer reviewed publications and chapters

-   Herbert, A. V., Haberle, S. G., **Flantua, S. G. A.**, Mottl, O., Blois, J. L., Williams, J. W., George, A., and Hope, G. S., **2024**. The Indo--Pacific Pollen Database -- a Neotoma constituent database, ***Climate of the Past*** 20, 2473--2485. [L](https://doi.org/10.5194/cp-20-2473-2024,%202024)[ink](https://cp.copernicus.org/articles/20/2473/2024/)

-   Schafstall, N.B., Benito, X., Brugger, S.O., Davies, A.L., Ellis, E., Pla-Rabes, S., Bonk, A., Bunting, J., Chambers, F.M., **Flantua, S.G.A.**, Fletcher, T.L., Greiser, C., Hernandez, A., Keenan, B., Koren, G., Marcisz, K., Montoya, E., Quesada-Román, A., Ratnayake, A.S., Sabatier, P., Smol, J.P., Suárez-Mozo, Y.S., **2024**. Ten simple rules to bridge ecology and palaeoecology by publishing outside palaeo-ecological journals. ***PLOS ONE***. [Link](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1012487).

-   Hooghiemstra, H. Berrio J-C, Torres, V., Bogotá-A, R.B:, Groot, M., Hoorn, C., **Flantua, S.G.A.** **2024**. Pollen records of Northern South America: Quaternary history. ***Encyclopedia of Quaternary Science***. Third edition, Elsevier, 2024.

-   Pacheco-Riaño, L.C., Rumpf, S., Maliniemi, T., **Flantua, S.G.A.\***, Grytnes, J.-A.\*, **2024**. Reliability of presence-only data for assessing plant community responses to climate warming. ***Ecography***, e07213. <https://doi.org/10.1111/ecog.07213>. [Link](https://nsojournals.onlinelibrary.wiley.com/doi/10.1111/ecog.07213). *(\* senior authors)*

-   Sayedi, S.S., Abbott, B.W., Vannière, B., Leys, B., Colombaroli, D., Romera, G.G., Słowiński, M., Aleman, J.C., Blarquez, O., Feurdean, A., Brown, K., Aakala, T., Alenius, T., Allen, K., Andric, M., Bergeron, Y., Biagioni, S., Bradshaw, R., Bremond, L., Brisset, E., Brooks, J., Brugger, S.O., Brussel, T., Cadd, H., Cagliero, E., Carcaillet, C., Carter, V., Catry, F.X., Champreux, A., Chaste, E., Chavardès, R.D., Chipman, M., Conedera, M., Connor, S., Constantine, M., Courtney Mustaphi, C., Dabengwa, A.N., Daniels, W., De Boer, E., Dietze, E., Estrany, J., Fernandes, P., Finsinger, W., **Flantua, S.G.A.**, Fox-Hughes, P., Gaboriau, D.M., M.Gayo, E., Girardin, Martin.P., Glenn, J., Glückler, R., González-Arango, C., Groves, M., Hamilton, D.S., Hamilton, R.J., Hantson, S., Hapsari, K.A., Hardiman, M., Hawthorne, D., Hoffman, K., Inoue, J., Karp, A.T., Krebs, P., Kulkarni, C., Kuosmanen, N., Lacourse, T., Ledru, M.-P., Lestienne, M., Long, C., López-Sáez, J.A., Loughlin, N., Niklasson, M., Madrigal, J., Maezumi, S.Y., Marcisz, K., Mariani, M., McWethy, D., Meyer, G., Molinari, C., Montoya, E., Mooney, S., Morales-Molino, C., Morris, J., Moss, P., Oliveras, I., Pereira, J.M., Pezzatti, G.B., Pickarski, N., Pini, R., Rehn, E., Remy, C.C., Revelles, J., Rius, D., Robin, V., Ruan, Y., Rudaya, N., Russell-Smith, J., Seppä, H., Shumilovskikh, L., T.Sommers, W., Tavşanoğlu, Ç., Umbanhowar, C., Urquiaga, E., Urrego, D., Vachula, R.S., Wallenius, T., You, C., Daniau, A.-L., **2024**. Assessing changes in global fire regimes. ***Fire Ecology** 20*, 18. [Link](https://doi.org/10.1186/s42408-023-00237-9)

-   **Flantua, S.G.A.**, Hooghiemstra, H., **2023**. Anthropogenic pollen indicators: Global food plants and Latin American human indicators in the pollen record. ***Nature Scientific Data*** 10, 721. [Link](https://www.nature.com/articles/s41597-023-02613-1).

-   Gallou, A., Jump, A.S., Lynn, J.S., Field, R., Irl, S.D.H., Steinbauer, M.J., Beierkuhnlein, C., Chen, J.-C., Chou, C.-H., Hemp, A., Kidane, Y., König, C., Kreft, H., Naqinezhad, A., Nowak, A., Nuppenau, J.-N., Trigas, P., Price, J.P., Roland, C.A., Schweiger, A.H., Weigelt, P., **Flantua, S.G.A.\***, Grytnes, J.-A.\*, **2023**. Diurnal temperature range as a key predictor of plants' elevation ranges globally*. **Nature Communications***14, 7890. [Link](https://www.nature.com/articles/s41467-023-43477-8)*.* (\**senior authors*)

-   Birks, H.J.B., Bhatta, K.P., Felde, V.A., **Flantua, S.G.A.**, Mottl, O., Haberle, S.G., Herbert, A., Hooghiemstra, H., Birks, H.H., Grytnes, J.-A., Seddon, A.W.R., **2023**. Approaches to pollen taxonomic harmonisation in Quaternary palynology. ***Review of Palaeobotany and Palynology*** 319, 104989. https://doi.org/10.1016/j.revpalbo.2023.104989. [Link](https://doi.org/10.1016/j.revpalbo.2023.104989).

-   Van der Sande, M., Bush, M., Akesson, C.M., Berrio, J-C, Correa-Metrío, A., **Flantua, S.G.A.**, Hooghiemstra, H., Maezumi, S.Y., McMichael, C.N.H., Montoya, E., Mosblech, N.A.S., Nascimento, M. de Novaes, Peña-Claros, M., Poorter, L., Raczka, M.F., Gosling, W.D. (2023). Warming, drought and disturbances lead to shifts in functional composition; a millennial-scale analysis for Amazonian and Andean sites. *Global Change Biology*. [Link](https://doi.org/10.1111/gcb.16818){.uri}

-   Pacheco-Riaño, C., **Flantua, S.G.A.\***, Grytnes, J-A.\* 2023. Can Plants "Move" Fast Enough to Escape Climate Change? *Frontiers for Young Minds.* (\**senior authors*) [Link](https://kids.frontiersin.org/articles/10.3389/frym.2023.947230){.uri}

-   **Flantua, S.G.A.\***, Mottl., O.\*, Felde, V.A.\*, Bhatta, K.P.\*, Birks, H.H., Grytnes, JA, Seddon, A.W.R., Birks, H.J.B. 2023. A guide to the processing and standardization of global palaeoecological data for large-scale syntheses using fossil pollen. *Global Ecology and Biogeography,* [Link](https://doi.org/10.1111/geb.13693){.uri}. (\**first authors*)

-   Albert, J.S., Carnaval, A.C., **Flantua, S.G.A.**, Lohmann, L.G., Ribas, C.C., Riff, D., Carrillo, J.D., Fan, Y., Figueiredo, J.J.P., Guayasamin, J.M., Hoorn, C., de Melo, G.H., Nascimento, N., Quesada, C.A. Ulloa Ulloa, C., Val, P. Arieira, J., Encalada, A.C., Nobre, C.A. 2023. Human impacts outpace natural processes in the Amazon. *Science* 379(6630), [Link](https://www.science.org/doi/10.1126/science.abo5003)

-   Pacheco-Riaño, L.C., Schei, F.H., **Flantua, S.G.A.\***, Grytnes, J-A.\* 2023. Lags in the response of plant assemblages to global warming depends on temperature-change velocity. *Global Ecology and Biogeography.* [Link](https://onlinelibrary.wiley.com/doi/10.1111/geb.13653)  (\**senior author*s)

-   Bhatta, K. P., Mottl, O., Felde, V. A., **Flantua, S. G. A.**, Birks, H. H., Cao, X., Chen, F., Grytnes, J.-A., Seddon, A. W. R., & Birks, H. J. B. (2023). Exploring spatio-temporal patterns of palynological changes in Asia during the Holocene. *Frontiers in Ecology and Evolution*, 11. [Link](https://www.frontiersin.org/articles/10.3389/fevo.2023.1115784){.uri}

-   Hooghiemstra, H., Cleef, A.M., **Flantua, S.G.A.**, 2022. A paleoecological context to assess the development of oak forest in Colombia: A comment on Zorilla-Azcué, S., Gonzalez-Rodríguez, A., Oyama, K., González, M.A., & Rodríguez-Correa, H., The DNA history of a lonely oak: Quercus humboldtii phylogeography in the Colombian Andes. *Ecology and Evolution* 2021, doi: 10.100-2/ece3.7529. Ecology and Evolution 12, e8702. [Link](https://doi.org/10.1002/ece3.8702){.uri}

-   O'Dea, A., **Flantua, S.G.A.**, Leray, M., Lueders-Dumont, J.A., Titcomb. M.C.. 2022. Pleistocene sea level changes and crocodile population histories on the Isthmus of Panama: A comment on Avila-Cervantes et al. (2020). *Evolution.*

-   Tovar, C., Carril, A.F., Gutierrez, A.G., Ahrends, A., Fita, L., Zaninelli, P., Flombaum, O., Abarzua, A.M., Alarcon, D., Aschero, V., Baez, S., Barros, A., Carilla, J., Eugenia Ferrero, M., **Flantua S.G.A.**, Gonzáles, P., Menéndez C.G., Pérez-Escobar, O.A., Pauchard, A., Ruscica, R.C., Sarkinen, T., Sörensson, A.A., Srur, A., Villalba, R., Hollingsworth, P.M. 2022. Understanding climate change impacts on plant distributions in the Andes: challenges and opportunities. *Journal of Biogeography*. [Link](https://onlinelibrary.wiley.com/doi/full/10.1111/jbi.14389)

-   Hooghiemstra\*, H., Sarmiento Pérez, G., Torres Torres, V., Berrío, J-C., Lourens, L., **Flantua, S.G.A.**\* 2022. 60 years of scientific deep drilling in Colombia: the north Andean guide to the Quaternary. Scientific Drilling 10, 1-15. (\* *senior authors*)

-   Sales, R., McMichael, M., **Flantua, S.G.A.**, Hagemans, K., Zondervan, Z.R., González-Arango, C., Church, W., Bush, M. 2022. Potential distributions of pre-Columbian people in Tropical Andean landscapes. *Proceedings of the Royal Society Biological Sciences* 20200502. [Link](https://doi.org/10.1098/rstb.2020.0502).

-   Bacon, C.D., Gutiérrez-Pinto, N., **Flantua, S.**, Castellanos Suárez, D., Jaramillo, C., Pennington, R.T., Antonelli, A., 2021. The seasonally dry tropical forest species *Cavanillesia chicamochae* has a middle Quaternary origin. *Biotropica* 54 (1), 91-99. [Link](https://doi.org/10.1111/btp.13031)

-   Bradshaw, R.H.W., Styles, B., Giesecke, T., **Flantua, S.G.A.**, Bittmann, F., Williams, J.W., 2021. Eric C. Grimm 1951--2020. *Veget Hist Archaeobot*. [Link](https://doi.org/10.1007/s00334-021-00828-z)

-   Mottl, O.\*, **Flantua, S.G.A.**\*, Bhatta, K.P., Felde, V.A., Giesecke, T., Goring, S., Grimm, E.C., Haberle, S., Hooghiemstra, H., Ivory, S., Kuneš, P., Wolters, S., Seddon, A., Williams, J.W., 2021. Global acceleration in rates of vegetation change over the last 18,000 years. *Science* 372 (860-864). (\* first authors) [Link](https://science.sciencemag.org/content/372/6544/860)

-   Diazgranados\*, M., Tovar, C., Etherington, T.R., Rodríguez-Zorro, P., Castellanos-Castro, C., Galvis Rueda, M., **Flantua\*, S.G.A**. Ecosystem services show variable responses to future climate conditions in the high Andes. *PeerJ*. (2021) e11370. [Link](https://peerj.com/articles/11370) (\* *corresponding authors*

-   Mottl, O., Grytnes, J.-A., Seddon, A.W.R., Steinbauer, M.J., Bhatta, K.P., Felde, V.A., **Flantua, S.G.A.**, Birks, H.J.B., 2021. Rate-of-change analysis in paleoecology revisited: A new approach. *Review of Palaeobotany and Palynology* 293, 104483. [Link](https://doi.org/10.1016/j.revpalbo.2021.104483) ([preprint](https://www.biorxiv.org/content/10.1101/2020.12.16.422943v1))

-   Hooghiemstra, H., **Flantua, S.,** 2020. Book review: Quaternary ecology, evolution, and biogeography, Valenti Rull. Academic Press, Elsevier (2020). *Quaternary Science Reviews* 247, 106608. [Link](https://doi.org/10.1016/j.quascirev.2020.106608).

-   **Flantua, S.G.A.**, Payne, D., Borregaard, M.K., Beierkuhnlein, C., Steinbauer, M.J., Dullinger, S., Essl, F., Irl, S.D.H., Kienle, D., Kreft, H., Lenzner, B., Norder, S.J., Rijsdijk, K.R., Rumpf, S.B., Weigelt, P., Field, R., 2020. Snapshot isolation and isolation history challenge the analogy between mountains and islands used to understand endemism. *Global Ecology and Biogeography* 29 (10): 1651-1673. [Link](https://onlinelibrary.wiley.com/doi/epdf/10.1111/geb.13155)

-   Nürk, N.M., Linder, H.P., Onstein, R.E., Larcombe, M.J., Hughes, C.E., Fernández, L.P., Schlüter, P.M., Valente, L.M., Beierkuhnlein, C., Cutts, V., Donoghue, M.J., Edwards, E.J., Field, R., **Flantua, S.G.A.**, Higgins, S.I., Jentsch, A., Liede-Schumann, S., Pirie, M.D., 2020. Diversification in evolutionary arenas -- assessment and synthesis. *Ecology and Evolution*. [Link](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.6313) ([preprint](https://doi.org/10.1101/636803))

-   Onstein, R.E., Vink, D.N., Veen, J., Barratt, C.D., **Flantua, S.G.A.**, Wich, S.A., Kissling, W.D., 2020. Palm fruit colours are linked to the broad-scale distribution and diversification of primate colour vision systems. *Proceedings of the Royal Society Biological Sciences*. 287: 20192731. [Link](http://doi.org/10.1098/rspb.2019.2731)

-   Bilbao et al., 2019. Transforming fire suppression into an intercultural and participative fire management policy in Canaima National Park, Venezuela. A learning together and Indigenous, academic and institutional knowledge integration process. *Biodiversidade Brasileira-BioBrasil* 1, 316. [Link](https://revistaeletronica.icmbio.gov.br/BioBR/article/view/1345/971)

-   Felde, V.A., **Flantua, S.G.A.**, Jenks, C.R., Benito, B.M., de Beaulieu, J.-L., Kuneš, P., Magri, D., Nalepka, D., Risebrobakken, B., ter Braak, C.J.F., Allen, J.R.M., Granoszewski, W., Helmens, K.F., Huntley, B., Kondratienė, O., Kalniņa, L., Kupryjanowicz, M., Malkiewicz, M., Milner, A.M., Nita, M., Noryśkiewicz, B., Pidek, I.A., Reille, M., Salonen, J.S., Šeirienė, V., Winter, H., Tzedakis, P.C., Birks, H.J.B., 2019. Compositional turnover and variation in Eemian pollen sequences in Europe. *Vegetation History and Archaeobotany* 29, 101-109. [Link](https://doi.org/10.1007/s00334-019-00726-5)

-   **Flantua, S.G.A.**, O'Dea, A., Onstein, R., Giraldo, C., Hooghiemstra, H., 2019. The flickering connectivity system of the north Andean páramos. *Journal of Biogeography* 46, 1808-1825. [Link](https://doi.org/10.1111/jbi.13607)

-   Montade, V., Ledru M.P., Giesecke, T., **Flantua, S.G.A.**, Behling, H., Peyron, O., 2019. A new modern pollen dataset describing the Brazilian Atlantic Forest. *The Holocene* 29(8), 1253-1262. [Link](https://doi.org/10.1177%2F0959683619846981)

-   Hooghiemstra, H. & **Flantua, S.G.A.**, 2019. Colombia in the Quaternary: an overview of environmental and climatic change, in: Gómez, J., Pinilla--Pachon, A.O. (Eds.), The Geology of Colombia. Servicio Geológico Colombiano, Bogotá, pp. 43--104. [Link](https://www2.sgc.gov.co/LibroGeologiaColombia/Paginas/v4ch2.aspx)

-   Antonelli\*, A., Kissling\*, W.D., **Flantua\*, S.G.A.**, Bermúdez, M.A., Mulch, A., Muellner-Riehl, A.N., Kreft, H., Linder, H.P., Badgley, C., Fjeldså, J., Fritz, S.A., Rahbek, C., Herman, F., Hooghiemstra, H., Hoorn\*, C., 2018. Geological and climatic determinants of mountain biodiversity. *Nature Geoscience* 11, 718--725. (\* first co-authorship). [Link](https://www.nature.com/articles/s41561-018-0236-z/)

-   **Flantua, S.G.A.** & Hooghiemstra, H., 2018. Historical connectivity and mountain biodiversity; with special reference to Andean plants. In: Hoorn C., Perrigo, A., Antonelli A. (eds.), Mountains, Climate and Biodiversity. Chapter 12, Wiley. 171-185

-   Hoorn, C., Bogotá-Angel, G.R., Romero-Baez, M., Lammertsma, E.I., **Flantua, S.G.A.**, Dantas, E.I., Dino, R., do Carmo, D.A., Chemale Jr, F., 2017. The Amazon at Sea: Onset and stages of the Amazon River from a marine record, with special reference to Neogene plant turnover in the drainage basin. *Global and Planetary Change* 153, 51-65. [Link](https://doi.org/10.1016/j.gloplacha.2017.02.005)

-   Salamanca, S.S., Van Soelen, E.E., Van Manen, M.L.T., **Flantua, S.G.A.**, Santos, R.V., Roddaz, M., Dantas, E.L., Van Loon, E., Sinninghe Damsté, J.S., Kim, J.H., Hoorn, C., 2016. Amazon forest dynamics under changing abiotic conditions in the early Miocene (Colombian Amazonia*). Journal of Biogeography* 43(12), 2424-2437. [Link](https://doi.org/10.1111/jbi.12769)

-   **Flantua, S.G.A.**, Hooghiemstra, H., Vuille, M., Behling, H., Carson, J.F., Gosling, W.D., Hoyos, I., Ledru, M.P., Montoya, E., Mayle, F., Maldonado, A., Rull, V., Tonello, M.S., Whitney, B.S., González-Arango, C., 2016a. Climate variability and human impact in South America during the last 2000 years: synthesis and perspectives from pollen records. *Climate of the Past* 12, 483--523. [Link](https://doi.org/10.5194/cp-12-483-2016)

-   **Flantua, S.G.A.**, Blaauw, M., Hooghiemstra, H., 2016b. Geochronological database and classification system for age uncertainties in Neotropical pollen records. *Climate of the Past* 12, 387--414. [Link](https://doi.org/10.5194/cp-12-387-2016)

-   **Flantua, S.G.A.**, Hooghiemstra, H., Grimm, E.C., Behling, H., Bush, M.B., González-Arango, C., Gosling, W.D., Ledru, M.-P., Lozano-García, S., Maldonado, A., Prieto, A.R., Rull, V., Van Boxel, J.H., 2015. Updated site compilation of the Latin American Pollen Database. *Review of Palaeobotany and Palynology* 223, 104--115. [Link](https://doi.org/10.1016/j.revpalbo.2015.09.008)

-   Hoorn, H. & **Flantua, S.G.A.** 2015. An early start for the Panama land bridge. *Science* 348 (6231):186-187. [Link](doi:%2010.1126/science.aab0099)

-   **Flantua, S.G.A.**, Hooghiemstra, H., Van Boxel, J.H., Cabrera, M., González-Carranza, Z., González-Arango, C. 2014. Connectivity dynamics since the Last Glacial Maximum in the northern Andes; a pollen-driven framework to assess potential migration. In: W.D. Stevens, O.M. Montiel, P. Raven (eds.) Monographs in Systematic Botany Missouri Botanical Garden 128, 98-123. Paleobotany and Biogeography: A Festschrift for Alan Graham in His 80th Year. Missouri Botanical Garden Press, St Louis, MO. ISBN 978-0-915279-97-5 [Link](https://www.researchgate.net/publication/263275567_Connectivity_dynamics_since_the_Last_Glacial_Maximum_in_the_northern_Andes_a_pollen-driven_framework_to_assess_potential_migration)

-   Grimm, E.C., Bradshaw, R.H.W., **Flantua, S.G.A.**, Giesecke, T., Lézine, A.M., Takahara, H., Williams. J.W. 2013. Databases and their application. In: S.A. Elias (ed.) The Encyclopedia of Quaternary Science 3, pp. 831-838. Elsevier, Amsterdam. ISBN: 978-0-444-53642-6

-   **Flantua, S.G.A.**, Bilbao, B., Rosales, J. 2013. Indigenous land use and land cover changes in the National Park of Canaima, Venezuela: Pemón Sector II Kamarata. In: LT. Lopes, S. Arley, J. Silveira da Costa, E.R. Baptista (eds.). Libro Escudo Guianês, biodiversidade, conservação dos recursos naturais e cultura, pp.  209-224. NAEA, GSF, Belém, Georgetown. [Link](https://www.researchgate.net/publication/305815868_Indigenous_land_use_and_land_cover_changes_in_the_National_Park_of_Canaima_Venezuela_Pemon_Sector_II_Kamarata)

-   Rincon, A., Pascual, U., **Flantua, S.G.A.** 2013.  Examining spatially varying relationships between coca crops and associated factors in Colombia, using geographically weight regression. *Applied Geography* 37: 23-33. [Link](https://doi.org/10.1016/j.apgeog.2012.10.009)

-   Romero, M.H., **Flantua, S.G.A.**, Tansey, K., Berrío, J.C. 2012. Landscape transformation in savannas of northern South America: Land use / cover changes since 1987 in the Llanos Orientales of Colombia. *Applied Geography* 32: 766-776. [Link](https://doi.org/10.1016/j.apgeog.2011.08.010)

-   **Flantua, S.G.A.**, Boxel, v. J.H., Hooghiemstra, H., Smaalen, J. 2007. Application of GIS and logistic regression to fossil pollen data in modeling present and past spatial distribution of the Colombian savanna. *Climate Dynamics* 29(7-8): 697-712. [Link](https://doi.org/10.1007/s00382-007-0276-3)

------------------------------------------------------------------------

### Comments to other papers

-   Onstein, R.E., Vink, D.N., Veen, J., Barratt, C.D., **Flantua, S.G.A.**, Wich, S.A., Kissling, W.D., 2020. Understanding the relationship between fruit colour and primate vision requires multiple lines of evidence. A reply to Heymann & Fuzessy. *Proceedings of the Royal Society Biological Sciences* 288 (1943).

-   Hooghiemstra, H. & **Flantua, S.G.A.**. Interactive comment on "Early Pliocene vegetation and hydrology changes in western equatorial South America" by Friederike Grimmer et al*.". Clim. Past. Discussions.* [Link](https://cp.copernicus.org/preprints/cp-2017-129/cp-2017-129-SC2.pdf).

------------------------------------------------------------------------

### Popular Science Articles

-   Payne, D., Hoorn, C., Randin, C., **Flantua, S.G.A.**, 2020. Past changes in species diversity: A view from the mountains. *Past Global Changes Magazine* 28(1), 18-19. [Link](https://doi.org/10.22498/pages.28.1.18)

-   Morrison, K.D., Hammer, E., Popova, L., Madella, M., Whitehouse, N., Gaillard, M-J., LandCover6k Land-Use Group Members (**Flantua, S.G.A.**). Global-scale comparisons of human land use: developing shared terminology for land-use practices for global change. *Past Global Changes Magazine* 26(1), 8-9.

-   Van Boxel, J.H., Brandts, E.B., **Flantua, S.G.A.**, Grimm, E.C., Hooghiemstra, H., Van Loon, E.E., 2017. Data description for the DANS project: Disclosure of paleoecological datasets of IBED, FNWI, UvA. DANS Report.

-   Hooghiemstra, H., **Flantua, S.G.A.**, 2017. Hergebruik van data. LAPD -- Latin American Pollen Database. *Geobrief* 3, 14-16

-   **Flantua, S.G.A.**, Hooghiemstra, H., Grimm, E.C., Markgraf, V., 2013. Updated Latin American Pollen Database: Version 2013 in preparation for NEOTOMA. *Past Global Changes Magazine* 21, 88

------------------------------------------------------------------------

### Expert reports

-   Val, P., Figueiredo, J. Gustavo de Melo, Flantua, S.G.A., Quesada, C.A., Fan, Y., Albert, J.A., Guayasamin, J.M., Hoorn, C., 2021. Chapter 1: Geological History and Geodiversity of the Amazon. In: Nobre et al. Amazon Assessment Report 2021. United Nations Sustainable Development Solutions Network, New York, USA. https://www.theamazonwewant.org/spa-reports/. DOI: 10.55161/POFE6241

-   Rincón, S.A., Suárez, C.F., Romero-Ruiz M., **Flantua, S.G.A.**, Sarmiento, A., Hernández, N., Palacios Lozano, M.T., Naranjo, L.G., Usma, S. 2014. Identifying highly biodiverse savannas based on the European Union Renewable Energy Directive (SuLu Map): Conceptual background and technical guidance. WWF Colombia, Bogotá, 104 pp.

-   Bustamente, C., Osorio, F., Rojas, L., Cáceres, X, Romero-Ruiz, M., Sarmiento Dueñas, A., Flórez, N., Hernández, N., Porras, M., **Flantua, S.G.A.**, Vargas, M.C., Beltrán, D., Giménez, N., Tellez, P. 2013. Strategic management plan for the River Orinoco waterbasin, Colombia -   Phase I and II. Instituto de investigación de Recursos Biológicos Alexander von Humboldt -- 4D Elements Consultores S.A.S. -- INGEAG, Bogotá, 320 pp. (In Spanish)

-   Romero-Ruiz, M., **Flantua, S.G.A.**, Sarmiento, A., Hernández, N. 2013. Defining conservation areas in the Orinoco, Colombia: Analysis of studies completed or in progress. WWF Colombia, Bogotá, 38 pp.

-   **Flantua, S.G.A.,** Uribe B., C.E. 2001. Aproximación a una caracterización de la zona de influencia de la Quebrada Cameguada en el municipio de Chinchiná, Departamento de Caldas. Unidad Municipal de Asistencia Técnica Agropecuaria (UMATA). Chinchiná, Caldas, 56 pp.

------------------------------------------------------------------------

UNPUBLISHED THESES:

**Flantua, S.G.A.** (2017). Climate change and topography as drivers of Latin American biome dynamics. PhD thesis, University of Amsterdam. [Link](https://dare.uva.nl/search?identifier=be078e0a-6805-46ed-b8e4-96e5c9532c50)

**Flantua, S.G.A.** (2008). Land use and land-cover changes in the Sector II. Kamarata in the National Park Canaima, Venezuela. Master thesis II, University of Amsterdam.

**Flantua S.G.A.** (2005). Modelling the spatial distribution of the Colombian Savanna: Los Llanos Orientales. Master Thesis I, University of Amsterdam. [Link](https://www.researchgate.net/publication/234649927_FLANTUA_2005_MASTER_THESIS_MODELLING_THE_SPATIAL_DISTRIBUTION_OF_THE_COLOMBIAN_SAVANNAS_LLANOS_ORIENTALES)
